import type { FormTemplate } from './types';

export const FORM_TEMPLATES: FormTemplate[] = [
  // ==========================================
  // GENERAL
  // ==========================================
  {
    id: 'contact-form',
    name: 'Contact Form',
    description: 'A clean contact form to collect inquiries, support requests, and messages.',
    category: 'General',
    icon: '✉️',
    fields: [
      {
        id: 't_contact_header',
        type: 'heading',
        label: 'Contact Us',
        width: 12,
      },
      {
        id: 't_contact_fname',
        type: 'text',
        label: 'First Name',
        placeholder: 'Jane',
        required: true,
        width: 6,
      },
      {
        id: 't_contact_lname',
        type: 'text',
        label: 'Last Name',
        placeholder: 'Doe',
        required: true,
        width: 6,
      },
      {
        id: 't_contact_email',
        type: 'email',
        label: 'Email Address',
        placeholder: 'jane.doe@example.com',
        required: true,
        width: 6,
      },
      {
        id: 't_contact_phone',
        type: 'phone',
        label: 'Phone Number',
        placeholder: '+1 (555) 000-0000',
        required: false,
        width: 6,
      },
      {
        id: 't_contact_subject',
        type: 'dropdown',
        label: 'Subject',
        placeholder: 'Select an inquiry reason',
        options: ['General Inquiry', 'Customer Support', 'Sales & Pricing', 'Partnership'],
        required: true,
        width: 12,
      },
      {
        id: 't_contact_message',
        type: 'textarea',
        label: 'Message',
        placeholder: 'Tell us how we can help you...',
        required: true,
        width: 12,
      },
    ],
  },
  {
    id: 'feedback-form',
    name: 'Feedback Form',
    description: 'Gather user satisfaction ratings, feedback notes, and follow-up permissions.',
    category: 'General',
    icon: '💬',
    fields: [
      {
        id: 't_feedback_header',
        type: 'heading',
        label: 'We Value Your Feedback',
        width: 12,
      },
      {
        id: 't_feedback_intro',
        type: 'paragraph',
        label: 'Please take a minute to help us improve our services and product experience.',
        width: 12,
      },
      {
        id: 't_feedback_rating',
        type: 'radio',
        label: 'Overall Satisfaction',
        options: ['Excellent', 'Good', 'Average', 'Poor'],
        required: true,
        width: 12,
      },
      {
        id: 't_feedback_highlight',
        type: 'text',
        label: 'What did you like most?',
        placeholder: 'e.g. Fast response, intuitive interface',
        required: false,
        width: 12,
      },
      {
        id: 't_feedback_improvements',
        type: 'textarea',
        label: 'What could we do better?',
        placeholder: 'Share any suggestions or areas for improvement...',
        required: false,
        width: 12,
      },
      {
        id: 't_feedback_followup',
        type: 'radio',
        label: 'May we contact you to discuss your feedback?',
        options: ['Yes', 'No'],
        required: true,
        width: 12,
      },
      {
        id: 't_feedback_email',
        type: 'email',
        label: 'Contact Email',
        placeholder: 'your.name@example.com',
        required: true,
        width: 12,
        visibleIf: {
          combinator: 'and',
          conditions: [{ fieldId: 't_feedback_followup', operator: 'equals', value: 'Yes' }],
        },
      },
    ],
  },
  {
    id: 'customer-survey',
    name: 'Customer Survey',
    description: 'Evaluate customer satisfaction, product usage patterns, and recommendations.',
    category: 'General',
    icon: '📊',
    fields: [
      {
        id: 't_survey_header',
        type: 'heading',
        label: 'Customer Experience Survey',
        width: 12,
      },
      {
        id: 't_survey_product',
        type: 'dropdown',
        label: 'Primary Product or Service Used',
        options: ['Cloud Platform', 'Professional Services', 'Developer Tools', 'Mobile App'],
        required: true,
        width: 6,
      },
      {
        id: 't_survey_frequency',
        type: 'dropdown',
        label: 'How often do you use our product?',
        options: ['Daily', 'Weekly', 'Monthly', 'First Time'],
        required: true,
        width: 6,
      },
      {
        id: 't_survey_nps',
        type: 'radio',
        label: 'How likely are you to recommend us to a colleague?',
        options: ['10 - Extremely Likely', '8-9 - Likely', '6-7 - Neutral', '0-5 - Unlikely'],
        required: true,
        width: 12,
      },
      {
        id: 't_survey_reason',
        type: 'textarea',
        label: 'What is the primary reason for your score?',
        placeholder: 'Describe your experience...',
        required: false,
        width: 12,
      },
      {
        id: 't_survey_comments',
        type: 'textarea',
        label: 'Any additional comments or feature requests?',
        placeholder: 'Optional thoughts...',
        required: false,
        width: 12,
      },
    ],
  },

  // ==========================================
  // BUSINESS
  // ==========================================
  {
    id: 'job-application',
    name: 'Job Application',
    description: 'Applicant profile with role selection, experience, portfolio, and resume attachment.',
    category: 'Business',
    icon: '💼',
    fields: [
      {
        id: 't_job_header',
        type: 'heading',
        label: 'Employment Application',
        width: 12,
      },
      {
        id: 't_job_fname',
        type: 'text',
        label: 'First Name',
        placeholder: 'Alex',
        required: true,
        width: 6,
      },
      {
        id: 't_job_lname',
        type: 'text',
        label: 'Last Name',
        placeholder: 'Morgan',
        required: true,
        width: 6,
      },
      {
        id: 't_job_email',
        type: 'email',
        label: 'Email Address',
        placeholder: 'alex.morgan@domain.com',
        required: true,
        width: 6,
      },
      {
        id: 't_job_phone',
        type: 'phone',
        label: 'Phone Number',
        placeholder: '+1 (555) 234-5678',
        required: true,
        width: 6,
      },
      {
        id: 't_job_role',
        type: 'dropdown',
        label: 'Position Applied For',
        options: [
          'Senior Full Stack Engineer',
          'Frontend Specialist',
          'Backend Infrastructure Engineer',
          'Product Designer (UI/UX)',
          'Engineering Manager',
        ],
        required: true,
        width: 12,
      },
      {
        id: 't_job_experience',
        type: 'number',
        label: 'Years of Professional Experience',
        placeholder: '4',
        required: true,
        width: 6,
      },
      {
        id: 't_job_startdate',
        type: 'date',
        label: 'Earliest Available Start Date',
        required: true,
        width: 6,
      },
      {
        id: 't_job_portfolio',
        type: 'text',
        label: 'LinkedIn or Portfolio URL',
        placeholder: 'https://linkedin.com/in/...',
        required: false,
        width: 12,
      },
      {
        id: 't_job_resume',
        type: 'file',
        label: 'Resume / Curriculum Vitae',
        file: { maxSizeMb: 10, acceptedMimeTypes: ['application/pdf', 'application/msword'] },
        required: true,
        width: 12,
      },
      {
        id: 't_job_cover',
        type: 'textarea',
        label: 'Cover Letter / Candidate Statement',
        placeholder: 'Briefly introduce yourself and what excites you about this role...',
        required: false,
        width: 12,
      },
    ],
  },
  {
    id: 'employee-onboarding',
    name: 'Employee Onboarding',
    description: 'Collect new hire personal details, emergency contacts, and identification documents.',
    category: 'Business',
    icon: '🏢',
    fields: [
      {
        id: 't_onboard_header',
        type: 'heading',
        label: 'New Hire Onboarding Form',
        width: 12,
      },
      {
        id: 't_onboard_fullname',
        type: 'text',
        label: 'Full Legal Name',
        placeholder: 'Jordan Taylor Smith',
        required: true,
        width: 12,
      },
      {
        id: 't_onboard_email',
        type: 'email',
        label: 'Personal Email Address',
        placeholder: 'jordan.smith@gmail.com',
        required: true,
        width: 6,
      },
      {
        id: 't_onboard_phone',
        type: 'phone',
        label: 'Primary Phone Number',
        placeholder: '+1 (555) 789-0123',
        required: true,
        width: 6,
      },
      {
        id: 't_onboard_dob',
        type: 'date',
        label: 'Date of Birth',
        required: true,
        width: 6,
      },
      {
        id: 't_onboard_dept',
        type: 'dropdown',
        label: 'Department',
        options: ['Engineering', 'Product & Design', 'Marketing', 'Sales & RevOps', 'Human Resources'],
        required: true,
        width: 6,
      },
      {
        id: 't_onboard_emg_name',
        type: 'text',
        label: 'Emergency Contact Name',
        placeholder: 'Contact Full Name',
        required: true,
        width: 6,
      },
      {
        id: 't_onboard_emg_phone',
        type: 'phone',
        label: 'Emergency Contact Phone',
        placeholder: '+1 (555) 000-0000',
        required: true,
        width: 6,
      },
      {
        id: 't_onboard_idproof',
        type: 'file',
        label: 'Government ID Document',
        file: { maxSizeMb: 10, acceptedMimeTypes: ['application/pdf', 'image/jpeg', 'image/png'] },
        required: true,
        width: 12,
      },
    ],
  },
  {
    id: 'client-intake',
    name: 'Client Intake Form',
    description: 'Qualify new client engagements, scope, estimated budgets, and target timelines.',
    category: 'Business',
    icon: '🤝',
    fields: [
      {
        id: 't_client_header',
        type: 'heading',
        label: 'New Client Project Intake',
        width: 12,
      },
      {
        id: 't_client_company',
        type: 'text',
        label: 'Company / Organization Name',
        placeholder: 'Acme Corporation',
        required: true,
        width: 12,
      },
      {
        id: 't_client_contact',
        type: 'text',
        label: 'Primary Contact Person',
        placeholder: 'Taylor Reed',
        required: true,
        width: 6,
      },
      {
        id: 't_client_email',
        type: 'email',
        label: 'Work Email Address',
        placeholder: 'taylor@acme.com',
        required: true,
        width: 6,
      },
      {
        id: 't_client_service',
        type: 'dropdown',
        label: 'Requested Service',
        options: [
          'Full-Stack Web Development',
          'UI/UX Product Design',
          'Cloud Architecture & DevOps',
          'Security Audit & Consulting',
        ],
        required: true,
        width: 12,
      },
      {
        id: 't_client_budget',
        type: 'dropdown',
        label: 'Estimated Budget Range',
        options: ['$10,000 - $25,000', '$25,000 - $50,000', '$50,000 - $100,000', '$100,000+'],
        required: true,
        width: 6,
      },
      {
        id: 't_client_deadline',
        type: 'date',
        label: 'Target Launch Date',
        required: false,
        width: 6,
      },
      {
        id: 't_client_details',
        type: 'textarea',
        label: 'Project Summary & Key Deliverables',
        placeholder: 'Describe your vision, challenges, and goals...',
        required: true,
        width: 12,
      },
    ],
  },

  // ==========================================
  // EVENTS
  // ==========================================
  {
    id: 'event-registration',
    name: 'Event Registration',
    description: 'Attendee registration with ticket tiers, dietary preferences, and accommodations.',
    category: 'Events',
    icon: '🎟️',
    fields: [
      {
        id: 't_event_header',
        type: 'heading',
        label: 'Conference Registration',
        width: 12,
      },
      {
        id: 't_event_fullname',
        type: 'text',
        label: 'Full Name',
        placeholder: 'Sam Davis',
        required: true,
        width: 12,
      },
      {
        id: 't_event_email',
        type: 'email',
        label: 'Email Address',
        placeholder: 'sam.davis@example.com',
        required: true,
        width: 6,
      },
      {
        id: 't_event_phone',
        type: 'phone',
        label: 'Phone Number',
        placeholder: '+1 (555) 987-6543',
        required: true,
        width: 6,
      },
      {
        id: 't_event_ticket',
        type: 'dropdown',
        label: 'Ticket Type',
        options: ['General Admission', 'VIP All-Access', 'Academic / Student Pass', 'Speaker Pass'],
        required: true,
        width: 6,
      },
      {
        id: 't_event_quantity',
        type: 'number',
        label: 'Number of Tickets',
        placeholder: '1',
        required: true,
        width: 6,
      },
      {
        id: 't_event_diet',
        type: 'radio',
        label: 'Dietary Preferences',
        options: ['Standard / None', 'Vegetarian', 'Vegan', 'Gluten-Free'],
        required: true,
        width: 12,
      },
      {
        id: 't_event_has_accommodations',
        type: 'radio',
        label: 'Do you require accessibility accommodations?',
        options: ['Yes', 'No'],
        required: true,
        width: 12,
      },
      {
        id: 't_event_accommodation_notes',
        type: 'textarea',
        label: 'Please specify your accessibility requirements',
        placeholder: 'e.g. Wheelchair access, sign language interpreter...',
        required: true,
        width: 12,
        visibleIf: {
          combinator: 'and',
          conditions: [{ fieldId: 't_event_has_accommodations', operator: 'equals', value: 'Yes' }],
        },
      },
    ],
  },
  {
    id: 'event-feedback',
    name: 'Event Feedback',
    description: 'Post-event survey covering keynote ratings, venue satisfaction, and recommendations.',
    category: 'Events',
    icon: '⭐',
    fields: [
      {
        id: 't_evfb_header',
        type: 'heading',
        label: 'Post-Event Feedback',
        width: 12,
      },
      {
        id: 't_evfb_rating',
        type: 'radio',
        label: 'Overall Event Experience',
        options: ['Outstanding', 'Very Good', 'Average', 'Poor'],
        required: true,
        width: 12,
      },
      {
        id: 't_evfb_favorite',
        type: 'text',
        label: 'Which session or speaker did you enjoy most?',
        placeholder: 'Speaker or workshop title...',
        required: false,
        width: 12,
      },
      {
        id: 't_evfb_organization',
        type: 'radio',
        label: 'Event Organization & Schedule Timing',
        options: ['Flawless', 'Acceptable', 'Needs Improvement'],
        required: true,
        width: 6,
      },
      {
        id: 't_evfb_venue',
        type: 'radio',
        label: 'Venue & Facilities',
        options: ['Great', 'Adequate', 'Disappointing'],
        required: true,
        width: 6,
      },
      {
        id: 't_evfb_attend_again',
        type: 'radio',
        label: 'Would you attend next year?',
        options: ['Definitely', 'Likely', 'Unlikely'],
        required: true,
        width: 12,
      },
      {
        id: 't_evfb_suggestions',
        type: 'textarea',
        label: 'Suggestions for Next Year',
        placeholder: 'Topics you want covered, logistical tips...',
        required: false,
        width: 12,
      },
    ],
  },

  // ==========================================
  // EDUCATION
  // ==========================================
  {
    id: 'student-registration',
    name: 'Student Registration',
    description: 'Enrollment form with academic major, contact information, and address fields.',
    category: 'Education',
    icon: '🎒',
    fields: [
      {
        id: 't_student_header',
        type: 'heading',
        label: 'Student Enrollment Form',
        width: 12,
      },
      {
        id: 't_student_fullname',
        type: 'text',
        label: 'Full Legal Name',
        placeholder: 'Casey Rivera',
        required: true,
        width: 12,
      },
      {
        id: 't_student_dob',
        type: 'date',
        label: 'Date of Birth',
        required: true,
        width: 6,
      },
      {
        id: 't_student_gender',
        type: 'dropdown',
        label: 'Gender',
        options: ['Female', 'Male', 'Non-Binary', 'Prefer not to disclose'],
        required: true,
        width: 6,
      },
      {
        id: 't_student_email',
        type: 'email',
        label: 'Student Email',
        placeholder: 'casey.rivera@edu.org',
        required: true,
        width: 6,
      },
      {
        id: 't_student_phone',
        type: 'phone',
        label: 'Phone Number',
        placeholder: '+1 (555) 123-4567',
        required: true,
        width: 6,
      },
      {
        id: 't_student_major',
        type: 'dropdown',
        label: 'Intended Degree Program',
        options: [
          'Computer Science & Engineering',
          'Data Science & AI',
          'Mechanical Engineering',
          'Biomedical Sciences',
          'Business Administration',
        ],
        required: true,
        width: 12,
      },
      {
        id: 't_student_address',
        type: 'text',
        label: 'Street Address',
        placeholder: '123 Campus Way, Apt 4B',
        required: true,
        width: 12,
      },
      {
        id: 't_student_city',
        type: 'text',
        label: 'City',
        placeholder: 'San Francisco',
        required: true,
        width: 4,
      },
      {
        id: 't_student_state',
        type: 'text',
        label: 'State / Province',
        placeholder: 'California',
        required: true,
        width: 4,
      },
      {
        id: 't_student_pincode',
        type: 'text',
        label: 'Postal / Zip Code',
        placeholder: '94107',
        required: true,
        width: 4,
      },
    ],
  },
  {
    id: 'scholarship-application',
    name: 'Scholarship Application',
    description: 'Higher education student financial aid and scholarship with conditional proof uploads and academic records.',
    category: 'Education',
    icon: '🎓',
    fields: [
      // 1. Personal Information
      {
        id: 't_schol_header_personal',
        type: 'heading',
        label: 'Personal Information',
        width: 12,
      },
      {
        id: 't_schol_fullname',
        type: 'text',
        label: 'Full Name',
        placeholder: 'Morgan Lee',
        required: true,
        width: 12,
      },
      {
        id: 't_schol_email',
        type: 'email',
        label: 'Email',
        placeholder: 'morgan.lee@university.edu',
        required: true,
        width: 6,
      },
      {
        id: 't_schol_phone',
        type: 'phone',
        label: 'Phone',
        placeholder: '+1 (555) 456-7890',
        required: true,
        width: 6,
      },
      {
        id: 't_schol_dob',
        type: 'date',
        label: 'Date of Birth',
        required: true,
        width: 12,
      },

      // 2. Contact Information
      {
        id: 't_schol_header_contact',
        type: 'heading',
        label: 'Contact Information',
        width: 12,
      },
      {
        id: 't_schol_address',
        type: 'text',
        label: 'Address',
        placeholder: '742 Evergreen Terrace, Suite 101',
        required: true,
        width: 12,
      },
      {
        id: 't_schol_city',
        type: 'text',
        label: 'City',
        placeholder: 'Springfield',
        required: true,
        width: 4,
      },
      {
        id: 't_schol_state',
        type: 'text',
        label: 'State',
        placeholder: 'Illinois',
        required: true,
        width: 4,
      },
      {
        id: 't_schol_pincode',
        type: 'text',
        label: 'Pincode',
        placeholder: '62704',
        required: true,
        width: 4,
      },

      // 3. Academic Information
      {
        id: 't_schol_header_academic',
        type: 'heading',
        label: 'Academic Information',
        width: 12,
      },
      {
        id: 't_schol_college',
        type: 'text',
        label: 'College',
        placeholder: 'State Institute of Technology',
        required: true,
        width: 6,
      },
      {
        id: 't_schol_course',
        type: 'text',
        label: 'Course',
        placeholder: 'B.S. in Computer Science',
        required: true,
        width: 6,
      },
      {
        id: 't_schol_year',
        type: 'dropdown',
        label: 'Academic Year',
        options: ['1st Year (Freshman)', '2nd Year (Sophomore)', '3rd Year (Junior)', 'Final Year (Senior)'],
        required: true,
        width: 6,
      },
      {
        id: 't_schol_cgpa',
        type: 'number',
        label: 'CGPA',
        placeholder: '3.85',
        required: true,
        width: 6,
      },

      // 4. Financial Information
      {
        id: 't_schol_header_financial',
        type: 'heading',
        label: 'Financial Information',
        width: 12,
      },
      {
        id: 't_schol_category',
        type: 'dropdown',
        label: 'Scholarship Category',
        options: ['Merit Scholarship', 'STEM Excellence Award', 'Need-Based Financial Aid', 'Leadership Grant'],
        required: true,
        width: 6,
      },
      {
        id: 't_schol_financial_aid',
        type: 'radio',
        label: 'Do you require financial assistance?',
        options: ['Yes', 'No'],
        required: true,
        width: 6,
      },
      {
        id: 't_schol_income',
        type: 'number',
        label: 'Annual Family Income ($)',
        placeholder: '45000',
        required: true,
        width: 6,
        visibleIf: {
          combinator: 'and',
          conditions: [{ fieldId: 't_schol_financial_aid', operator: 'equals', value: 'Yes' }],
        },
      },
      {
        id: 't_schol_financial_details',
        type: 'textarea',
        label: 'Financial Assistance Details',
        placeholder: 'Briefly explain family financial circumstances or special hardships...',
        required: false,
        width: 12,
        visibleIf: {
          combinator: 'and',
          conditions: [{ fieldId: 't_schol_financial_aid', operator: 'equals', value: 'Yes' }],
        },
      },

      // 5. Documents
      {
        id: 't_schol_header_docs',
        type: 'heading',
        label: 'Documents',
        width: 12,
      },
      {
        id: 't_schol_marksheet',
        type: 'file',
        label: 'Marksheet',
        file: { maxSizeMb: 15, acceptedMimeTypes: ['application/pdf'] },
        required: true,
        width: 12,
      },
      {
        id: 't_schol_income_cert',
        type: 'file',
        label: 'Income Certificate',
        file: { maxSizeMb: 10, acceptedMimeTypes: ['application/pdf', 'image/jpeg'] },
        required: true,
        width: 6,
        visibleIf: {
          combinator: 'and',
          conditions: [{ fieldId: 't_schol_financial_aid', operator: 'equals', value: 'Yes' }],
        },
      },
      {
        id: 't_schol_supporting_doc',
        type: 'file',
        label: 'Supporting Document',
        file: { maxSizeMb: 10, acceptedMimeTypes: ['application/pdf', 'image/jpeg'] },
        required: false,
        width: 6,
      },
    ],
  },
  {
    id: 'college-admission',
    name: 'College Admission',
    description: 'Undergraduate student college admission form with course preference and entrance exam details.',
    category: 'Education',
    icon: '🏛️',
    fields: [
      {
        id: 't_adm_header',
        type: 'heading',
        label: 'Undergraduate Admission Application',
        width: 12,
      },
      {
        id: 't_adm_name',
        type: 'text',
        label: 'Applicant Name',
        placeholder: 'Robin Vance',
        required: true,
        width: 12,
      },
      {
        id: 't_adm_email',
        type: 'email',
        label: 'Email',
        placeholder: 'robin.vance@gmail.com',
        required: true,
        width: 6,
      },
      {
        id: 't_adm_phone',
        type: 'phone',
        label: 'Phone',
        placeholder: '+1 (555) 345-6789',
        required: true,
        width: 6,
      },
      {
        id: 't_adm_prevschool',
        type: 'text',
        label: 'High School / Previous Institution',
        placeholder: 'St. Jude High School',
        required: true,
        width: 12,
      },
      {
        id: 't_adm_score',
        type: 'number',
        label: 'Graduation Percentage / GPA',
        placeholder: '92',
        required: true,
        width: 6,
      },
      {
        id: 't_adm_course',
        type: 'dropdown',
        label: 'Target Degree Program',
        options: ['B.Sc Computer Science', 'B.Tech Information Technology', 'B.Com Finance', 'B.A Economics'],
        required: true,
        width: 6,
      },
      {
        id: 't_adm_has_entrance',
        type: 'radio',
        label: 'Have you taken a standardized entrance examination?',
        options: ['Yes', 'No'],
        required: true,
        width: 12,
      },
      {
        id: 't_adm_exam_score',
        type: 'text',
        label: 'Entrance Exam Roll Number & Percentile',
        placeholder: 'Roll: EX-98124, 98.4th Percentile',
        required: true,
        width: 12,
        visibleIf: {
          combinator: 'and',
          conditions: [{ fieldId: 't_adm_has_entrance', operator: 'equals', value: 'Yes' }],
        },
      },
      {
        id: 't_adm_transcript',
        type: 'file',
        label: 'High School Academic Records',
        file: { maxSizeMb: 10, acceptedMimeTypes: ['application/pdf'] },
        required: true,
        width: 12,
      },
    ],
  },

  // ==========================================
  // OTHER
  // ==========================================
  {
    id: 'leave-application',
    name: 'Leave Application',
    description: 'Workplace time-off request with conditional medical certificate requirements.',
    category: 'Other',
    icon: '🏖️',
    fields: [
      {
        id: 't_leave_header',
        type: 'heading',
        label: 'Employee Absence Request',
        width: 12,
      },
      {
        id: 't_leave_name',
        type: 'text',
        label: 'Employee Name',
        placeholder: 'Chris Nolan',
        required: true,
        width: 6,
      },
      {
        id: 't_leave_empid',
        type: 'text',
        label: 'Employee ID',
        placeholder: 'EMP-4082',
        required: true,
        width: 6,
      },
      {
        id: 't_leave_type',
        type: 'dropdown',
        label: 'Leave Category',
        options: ['Annual Vacation', 'Sick / Medical Leave', 'Casual Leave', 'Parental Leave', 'Bereavement'],
        required: true,
        width: 12,
      },
      {
        id: 't_leave_start',
        type: 'date',
        label: 'Leave Start Date',
        required: true,
        width: 6,
      },
      {
        id: 't_leave_end',
        type: 'date',
        label: 'Leave End Date',
        required: true,
        width: 6,
      },
      {
        id: 't_leave_reason',
        type: 'textarea',
        label: 'Reason for Absence',
        placeholder: 'Explain the reason for taking leave...',
        required: true,
        width: 12,
      },
      {
        id: 't_leave_medical_cert',
        type: 'file',
        label: 'Medical Certificate / Doctor Note',
        file: { maxSizeMb: 10, acceptedMimeTypes: ['application/pdf', 'image/jpeg'] },
        required: true,
        width: 12,
        visibleIf: {
          combinator: 'and',
          conditions: [{ fieldId: 't_leave_type', operator: 'equals', value: 'Sick / Medical Leave' }],
        },
      },
      {
        id: 't_leave_handover',
        type: 'text',
        label: 'Handover Colleague / Emergency Coverage',
        placeholder: 'Colleague name or department contact',
        required: false,
        width: 12,
      },
    ],
  },
];
